language: ruby
script: "bundle exec rake test"
cache: bundler
dist: xenial
os: linux

rvm:
  - 2.5.1
  - 2.6.2

gemfile:
  - gemfiles/rails-5-0.gemfile
  - gemfiles/rails-latest-release.gemfile
  - gemfiles/rails-edge.gemfile

jobs:
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/rails-edge.gemfile

notifications:
  email: false