language: ruby
script: "bundle exec rake test"
cache: bundler
dist: xenial
os: linux

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2

gemfile:
  - gemfiles/rails-5-0.gemfile
  - gemfiles/rails-latest-release.gemfile
  - gemfiles/rails-edge.gemfile

notifications:
  email: false
