language: ruby
script: "bundle exec rake test"
sudo: false
cache: bundler

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

gemfile:
  - gemfiles/rails-5-0.gemfile
  - gemfiles/rails-5-1.gemfile
  - gemfiles/rails-5-2.gemfile

notifications:
email: false
