language: ruby
script: "bundle exec rake test"
sudo: false
cache: bundler

rvm:
  - 2.5.1
  - 2.6.2

gemfile:
  - gemfiles/rails-5-0.gemfile
  - gemfiles/rails-latest-release.gemfile
  - gemfiles/rails-edge.gemfile

matrix:
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/rails-edge.gemfile


notifications:
email: false
